# Generated by Django 4.2.9 on 2024-06-23 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dockerfile_instructions',
            fields=[
                ('id_instruction', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Mandatory'), (2, 'Optional')])),
                ('type_env', models.IntegerField(choices=[(1, 'Yes'), (2, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='Dockerfile_templates',
            fields=[
                ('id_template', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=255)),
                ('template_purpose', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dockerfiles',
            fields=[
                ('id_dockerfile', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(default='Default purpose', max_length=255)),
                ('name', models.CharField(default=models.CharField(default='Default purpose', max_length=255), max_length=255)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dockerfile_explanations',
            fields=[
                ('id_explanation', models.AutoField(primary_key=True, serialize=False)),
                ('explanation', models.TextField()),
                ('examples', models.TextField(default='No examples available')),
                ('options', models.TextField(default='No options available')),
                ('summary_explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.URLField(blank=True)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dockerfile_instructions')),
            ],
        ),
    ]
