# Generated by Django 4.2.9 on 2024-05-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_imagetext_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetext',
            name='purpose',
            field=models.TextField(default='Default purpose'),
        ),
    ]
