# Generated by Django 4.2.9 on 2024-06-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_dockerfiles_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dockerfiles',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dockerfile_explanations',
            constraint=models.UniqueConstraint(fields=('id_explanation', 'instruction'), name='unique_dockerfile_instruction'),
        ),
        migrations.AddConstraint(
            model_name='dockerfiles',
            constraint=models.UniqueConstraint(fields=('id_dockerfile', 'user'), name='unique_dockerfile_user'),
        ),
    ]
