# Generated by Django 4.2.9 on 2024-06-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_imagetext_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dockerfile_instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Mandatory'), (2, 'Optional')])),
                ('type_env', models.IntegerField(choices=[(1, 'Yes'), (2, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='Dockerfile_explanations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('summary_explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.URLField(blank=True)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dockerfile_instructions')),
            ],
        ),
    ]
