# Generated by Django 4.2.9 on 2024-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_dockerfile_instructions_imagetext_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerfile_explanations',
            name='examples',
            field=models.TextField(default='No examples available'),
        ),
        migrations.AddField(
            model_name='dockerfile_explanations',
            name='options',
            field=models.TextField(default='No options available'),
        ),
    ]
