# Generated by Django 4.2.9 on 2024-06-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_dockerfile_explanations_examples_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dockerfile_templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('template_purpose', models.TextField()),
                ('dockerfile_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
