# Generated by Django 4.2.9 on 2024-06-12 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_dockerfile_templates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dockerfile_templates',
            old_name='dockerfile_text',
            new_name='text',
        ),
    ]
